import { relations, sql } from 'drizzle-orm';
import { check, index, integer, primaryKey, real, sqliteTable, text, unique, uniqueIndex } from 'drizzle-orm/sqlite-core';

// technical-plan §4.1, initial slice (TKT-02). Later tickets add tables and columns in new migrations.
// Times are ISO-8601 UTC strings with milliseconds. JSON columns are text.
// Invariants that SQL constraints cannot express (append-only ledger, final-verdict trigger) live in
// the custom migration 0001_invariants.sql (§4.2).

/** Hash-chain ledger (§8.1). Append-only: UPDATE and DELETE abort (trigger). */
export const ledgerEntries = sqliteTable('ledger_entries', {
  seq: integer('seq').primaryKey(),
  prevHash: text('prev_hash').notNull(),
  kind: text('kind').notNull(),
  payload: text('payload').notNull(),
  payloadHash: text('payload_hash').notNull(),
  ts: text('ts').notNull(),
  entryHash: text('entry_hash').notNull().unique(),
});

const anchorSeq = () =>
  integer('anchor_seq')
    .notNull()
    .references(() => ledgerEntries.seq);

export const organisations = sqliteTable(
  'organisations',
  {
    id: text('id').primaryKey(),
    type: text('type', { enum: ['fpo', 'buyer', 'processor'] }).notNull(),
    name: text('name').notNull(),
    officePhone: text('office_phone'),
  },
  (t) => [check('organisations_type_check', sql`${t.type} IN ('fpo','buyer','processor')`)],
);

// ── Better Auth tables (TKT-04) ─────────────────────────────────────────────────────────────────
// Generated by the Better Auth CLI (`pnpm dlx auth@1.7.6 generate`, the 1.7 name of @better-auth/cli)
// from src/lib/auth/auth.ts and merged here unchanged, except: `role` gains its CHECK and `org_id` its
// foreign key to organisations (technical-plan §4.1). Their timestamps are Better Auth's own
// integer-millisecond columns; the app's provenance tables keep ISO-8601 text.

export const user = sqliteTable(
  'user',
  {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
    image: text('image'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    /** agent | admin | buyer (§10). Never accepted from a client (`input: false`). */
    role: text('role', { enum: ['agent', 'admin', 'buyer'] }).notNull(),
    /** The user's organisation; every org-scoped query takes it from the session (EVAL-080). */
    orgId: text('org_id')
      .notNull()
      .references(() => organisations.id),
  },
  (t) => [check('user_role_check', sql`${t.role} IN ('agent','admin','buyer')`), index('user_org_idx').on(t.orgId)],
);

export const session = sqliteTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    token: text('token').notNull().unique(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
);

export const account = sqliteTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: integer('access_token_expires_at', { mode: 'timestamp_ms' }),
    refreshTokenExpiresAt: integer('refresh_token_expires_at', { mode: 'timestamp_ms' }),
    scope: text('scope'),
    password: text('password'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
);

export const verification = sqliteTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
      .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
      .$onUpdate(() => /* @__PURE__ */ new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

export const farmers = sqliteTable('farmers', {
  id: text('id').primaryKey(),
  orgId: text('org_id')
    .notNull()
    .references(() => organisations.id),
  name: text('name').notNull(),
  identifier: text('identifier'),
  /** Random `PR-` + 8 Crockford base32; the only farmer ID ever public (EV16). */
  producerId: text('producer_id').notNull().unique(),
});

export const plots = sqliteTable(
  'plots',
  {
    id: text('id').primaryKey(),
    farmerId: text('farmer_id')
      .notNull()
      .references(() => farmers.id),
    crop: text('crop', { enum: ['arabica', 'robusta'] }).notNull(),
    geojson: text('geojson').notNull(),
    areaHa: real('area_ha').notNull(),
    registrationChecks: text('registration_checks'),
    registrationStale: integer('registration_stale').notNull().default(0),
    anchorSeq: anchorSeq(),
    createdAt: text('created_at').notNull(),
    updatedAt: text('updated_at').notNull(),
  },
  (t) => [
    check('plots_crop_check', sql`${t.crop} IN ('arabica','robusta')`),
    check('plots_registration_stale_check', sql`${t.registrationStale} IN (0,1)`),
  ],
);

/**
 * An issuer's certificate for a plot, recorded as an attestation (§4.1, TKT-13, DISC4): Udgam proves
 * only that the file has not changed since it was recorded, never that the plot is organic. The file
 * is stored content-addressed (`file_path` is relative to DATA_DIR) and `file_hash` is anchored.
 * Immutable and never deleted or replaced (triggers in the attestation_guards custom migration).
 */
export const attestations = sqliteTable(
  'attestations',
  {
    /** `AT-` + 8 Crockford base32. */
    id: text('id').primaryKey(),
    plotId: text('plot_id')
      .notNull()
      .references(() => plots.id),
    type: text('type', { enum: ['organic'] }).notNull(),
    /** SHA-256 (lowercase hex) of the certificate file. */
    fileHash: text('file_hash').notNull(),
    filePath: text('file_path').notNull(),
    issuer: text('issuer').notNull(),
    /** Calendar dates, `YYYY-MM-DD`. */
    validFrom: text('valid_from').notNull(),
    validTo: text('valid_to').notNull(),
    anchorSeq: anchorSeq(),
  },
  (t) => [check('attestations_type_check', sql`${t.type} IN ('organic')`), index('attestations_plot_idx').on(t.plotId)],
);

export const devices = sqliteTable('devices', {
  /** `DV-` + 8 Crockford base32. */
  id: text('id').primaryKey(),
  /** The agent's user id. The foreign key to Better Auth's `user` arrives with TKT-04. */
  agentId: text('agent_id').notNull(),
  publicKeyJwk: text('public_key_jwk').notNull(),
  keyThumbprint: text('key_thumbprint').notNull().unique(),
  enrolledAt: text('enrolled_at').notNull(),
  revokedAt: text('revoked_at'),
  lastSeq: integer('last_seq').notNull().default(0),
  lastEventHash: text('last_event_hash'),
  anchorSeq: anchorSeq(),
});

export const harvestEvents = sqliteTable(
  'harvest_events',
  {
    id: text('id').primaryKey(),
    /** No foreign key: a boundary-rejected event may name a plot that does not exist. */
    plotId: text('plot_id'),
    deviceId: text('device_id').references(() => devices.id),
    agentId: text('agent_id'),
    seq: integer('seq'),
    clientCapturedAt: text('client_captured_at'),
    serverReceivedAt: text('server_received_at').notNull(),
    lat: real('lat'),
    lng: real('lng'),
    accuracyM: real('accuracy_m'),
    cherryKg: real('cherry_kg'),
    prevEventHash: text('prev_event_hash'),
    /** The exact canonical string the phone signed (never re-serialised). */
    payload: text('payload').notNull(),
    /**
     * Unique among ACCEPTED events only (TKT-09, EV15/TP7 as refined in EXE): an identical signed payload
     * is accepted at most once, while a boundary refusal never blocks a later genuine capture of the same
     * payload. Each distinct refusal of one payload is anchored once (unique with its reason).
     */
    payloadHash: text('payload_hash').notNull(),
    signature: text('signature').notNull(),
    boundaryStatus: text('boundary_status', { enum: ['accepted', 'rejected'] }).notNull(),
    boundaryReason: text('boundary_reason'),
    /** Maintained by triggers (§4.2); the app never writes it. */
    finalVerdict: text('final_verdict', { enum: ['Verified', 'Needs Review', 'Rejected'] }),
    anchorSeq: anchorSeq(),
  },
  (t) => [
    check('harvest_events_boundary_status_check', sql`${t.boundaryStatus} IN ('accepted','rejected')`),
    check('harvest_events_device_check', sql`${t.deviceId} IS NOT NULL OR ${t.boundaryStatus} = 'rejected'`),
    index('harvest_events_device_idx').on(t.deviceId),
    index('harvest_events_plot_idx').on(t.plotId),
    uniqueIndex('harvest_events_accepted_payload_hash_unique').on(t.payloadHash).where(sql`boundary_status = 'accepted'`),
    // One anchored refusal per (payload, reason): after X, Y, X the third answer is the original X rejection.
    uniqueIndex('harvest_events_rejected_payload_reason_unique').on(t.payloadHash, t.boundaryReason).where(sql`boundary_status = 'rejected'`),
  ],
);

export const media = sqliteTable(
  'media',
  {
    id: text('id').primaryKey(),
    eventId: text('event_id')
      .notNull()
      .references(() => harvestEvents.id),
    path: text('path').notNull(),
    sha256: text('sha256').notNull(),
    size: integer('size').notNull(),
    mime: text('mime').notNull(),
    exif: text('exif'),
    thumbPath: text('thumb_path'),
  },
  // Not unique: a rejected replay still stores its row (§4.1).
  (t) => [index('media_sha256_idx').on(t.sha256), index('media_event_idx').on(t.eventId)],
);

export const verificationRuns = sqliteTable(
  'verification_runs',
  {
    id: text('id').primaryKey(),
    eventId: text('event_id')
      .notNull()
      .references(() => harvestEvents.id),
    runNo: integer('run_no').notNull(),
    verdict: text('verdict', { enum: ['Verified', 'Needs Review', 'Rejected'] }).notNull(),
    score: real('score').notNull(),
    checks: text('checks').notNull(),
    unavailableProviders: text('unavailable_providers').notNull(),
    configVersion: text('config_version').notNull(),
    configHash: text('config_hash').notNull(),
    createdAt: text('created_at').notNull(),
    anchorSeq: anchorSeq(),
  },
  (t) => [
    unique('verification_runs_event_run_unique').on(t.eventId, t.runNo),
    check('verification_runs_verdict_check', sql`${t.verdict} IN ('Verified','Needs Review','Rejected')`),
  ],
);

/**
 * An admin's decision on a Needs Review run (technical-plan §4.1, TKT-12, TP15). `signature` is by the
 * admin's server-held key `key_id` over jcs({ v:1, runId, eventId, newVerdict, reason, adminId, ts }),
 * anchored as admin_override. Triggers (admin_override_guards migration) set the event's final verdict,
 * refuse a hard-failed run, a batched event's run and a superseded run, and keep the row append-only.
 * The reason is public: it appears on the certificate (Review focus 5).
 */
export const adminOverrides = sqliteTable(
  'admin_overrides',
  {
    /** `AO-` + 12 Crockford base32. */
    id: text('id').primaryKey(),
    runId: text('run_id')
      .notNull()
      .unique()
      .references(() => verificationRuns.id),
    adminId: text('admin_id')
      .notNull()
      .references(() => user.id),
    newVerdict: text('new_verdict', { enum: ['Verified', 'Rejected'] }).notNull(),
    reason: text('reason').notNull(),
    signature: text('signature').notNull(),
    keyId: text('key_id').notNull(),
    createdAt: text('created_at').notNull(),
    anchorSeq: anchorSeq(),
  },
  (t) => [
    check('admin_overrides_verdict_check', sql`${t.newVerdict} IN ('Verified','Rejected')`),
    check('admin_overrides_reason_check', sql`length(trim(${t.reason})) >= 10`),
  ],
);

/**
 * Signed Merkle checkpoints over contiguous ledger ranges (§8.2, TKT-15). Append-only (trigger).
 * `merkle_root` and `prev_checkpoint_hash` are lowercase hex; `signature` is P1363 base64url by the
 * ledger key `key_id` (RFC 7638 kid) over the checkpoint statement.
 */
export const ledgerCheckpoints = sqliteTable(
  'ledger_checkpoints',
  {
    id: integer('id').primaryKey(),
    fromSeq: integer('from_seq')
      .notNull()
      .references(() => ledgerEntries.seq),
    toSeq: integer('to_seq')
      .notNull()
      .unique()
      .references(() => ledgerEntries.seq),
    merkleRoot: text('merkle_root').notNull(),
    prevCheckpointHash: text('prev_checkpoint_hash').notNull(),
    ts: text('ts').notNull(),
    keyId: text('key_id').notNull(),
    signature: text('signature').notNull(),
  },
  (t) => [check('ledger_checkpoints_range_check', sql`${t.fromSeq} <= ${t.toSeq}`)],
);

// ── Batches and custody (TKT-14, §4.1–§4.2) ─────────────────────────────────────────────────────
// Invariants (membership, aggregates, lock after transfer) are triggers in the custom migration
// *_batch_invariants.sql; the app's own checks are courtesy (S8, TP14).

/**
 * A batch of Verified pickings of one crop. `quantity_kg` and `integrity_score` are maintained by
 * triggers (Σ cherry_kg, MIN score of each member's latest run); the app never writes them. A batch is
 * inserted open and empty; after its custody transfer it is locked.
 */
export const batches = sqliteTable(
  'batches',
  {
    /** `B-` + 8 Crockford base32. */
    id: text('id').primaryKey(),
    orgId: text('org_id')
      .notNull()
      .references(() => organisations.id),
    crop: text('crop', { enum: ['arabica', 'robusta'] }).notNull(),
    status: text('status', { enum: ['open', 'transferred'] })
      .notNull()
      .default('open'),
    quantityKg: real('quantity_kg').notNull().default(0),
    /** Null only while the batch has no members (inside its creating transaction). */
    integrityScore: real('integrity_score'),
    /** First 12 hex of the batch_created entry hash (the certificate link's `h`, §8.3). */
    shortHash: text('short_hash').notNull(),
    anchorSeq: anchorSeq(),
    createdAt: text('created_at').notNull(),
  },
  (t) => [
    check('batches_crop_check', sql`${t.crop} IN ('arabica','robusta')`),
    check('batches_status_check', sql`${t.status} IN ('open','transferred')`),
    index('batches_org_idx').on(t.orgId),
  ],
);

/** Batch membership: an event is in at most one batch (CF-07). Fixed at creation (trigger). */
export const batchEvents = sqliteTable(
  'batch_events',
  {
    batchId: text('batch_id')
      .notNull()
      .references(() => batches.id),
    eventId: text('event_id')
      .notNull()
      .unique()
      .references(() => harvestEvents.id),
  },
  (t) => [index('batch_events_batch_idx').on(t.batchId)],
);

/**
 * A signed custody transfer (TP15): `signature` by the admin's server-held key `key_id` over
 * jcs({ v:1, batchId, fromOrg, toOrg, ts: transferred_at, adminId }). Append-only (trigger).
 */
export const custodyTransfers = sqliteTable(
  'custody_transfers',
  {
    id: text('id').primaryKey(),
    batchId: text('batch_id')
      .notNull()
      .references(() => batches.id),
    fromOrg: text('from_org')
      .notNull()
      .references(() => organisations.id),
    toOrg: text('to_org')
      .notNull()
      .references(() => organisations.id),
    adminId: text('admin_id')
      .notNull()
      .references(() => user.id),
    transferredAt: text('transferred_at').notNull(),
    signature: text('signature').notNull(),
    keyId: text('key_id').notNull(),
    anchorSeq: anchorSeq(),
  },
  (t) => [index('custody_transfers_batch_idx').on(t.batchId), index('custody_transfers_to_org_idx').on(t.toOrg)],
);

// ── Enrolment, plot assignment and rate limits (TKT-05) ─────────────────────────────────────────

/**
 * One-time phone enrolment codes (§10, EVAL-082). Only the SHA-256 of the 6-character code is stored;
 * single use (`used_at`), 24 h expiry, and `attempts` counts redemption attempts on this code.
 */
export const enrollmentCodes = sqliteTable(
  'enrollment_codes',
  {
    codeHash: text('code_hash').primaryKey(),
    agentId: text('agent_id')
      .notNull()
      .references(() => user.id),
    createdBy: text('created_by')
      .notNull()
      .references(() => user.id),
    expiresAt: text('expires_at').notNull(),
    usedAt: text('used_at'),
    attempts: integer('attempts').notNull().default(0),
  },
  (t) => [index('enrollment_codes_agent_idx').on(t.agentId)],
);

/**
 * Which agent may capture for which plot (GAP-2, TP5). A capture for a plot without a live row
 * (`revoked_at IS NULL`) for the device's agent is refused at the boundary (§6.4).
 */
export const agentPlots = sqliteTable(
  'agent_plots',
  {
    agentId: text('agent_id')
      .notNull()
      .references(() => user.id),
    plotId: text('plot_id')
      .notNull()
      .references(() => plots.id),
    assignedAt: text('assigned_at').notNull(),
    revokedAt: text('revoked_at'),
  },
  (t) => [primaryKey({ columns: [t.agentId, t.plotId] }), index('agent_plots_plot_idx').on(t.plotId)],
);

/** Fixed-window counters (no Redis, N3): `window_start` is epoch seconds, aligned to the window. */
export const rateLimits = sqliteTable(
  'rate_limits',
  {
    key: text('key').notNull(),
    windowStart: integer('window_start').notNull(),
    count: integer('count').notNull().default(0),
  },
  (t) => [primaryKey({ columns: [t.key, t.windowStart] })],
);

/**
 * Remote-sensing answers (technical-plan §4.1, §7, TKT-07). Keyed per plot, provider, kind, month bucket
 * (`static` for forest loss, `YYYY-MM` for NDVI) and geometry hash, so an edited polygon misses (EVAL-044).
 * Only successful, clear-sky answers are stored (remote-sensing/cache.ts); `response` is JSON
 * (`{ source, result }`; GFW's dataset version is `result.datasetVersion`). Not provenance: no anchor.
 */
export const remoteSensingCache = sqliteTable(
  'remote_sensing_cache',
  {
    plotId: text('plot_id').notNull(),
    provider: text('provider', { enum: ['gfw', 'sentinel-hub'] }).notNull(),
    kind: text('kind', { enum: ['loss', 'ndvi_history', 'ndvi_window'] }).notNull(),
    monthBucket: text('month_bucket').notNull(),
    geometryHash: text('geometry_hash').notNull(),
    response: text('response').notNull(),
    fetchedAt: text('fetched_at').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.plotId, t.provider, t.kind, t.monthBucket, t.geometryHash] }),
    check('remote_sensing_cache_provider_check', sql`${t.provider} IN ('gfw','sentinel-hub')`),
    check('remote_sensing_cache_kind_check', sql`${t.kind} IN ('loss','ndvi_history','ndvi_window')`),
  ],
);

/**
 * The season yield reference (technical-plan §4.1, §6.6, TP6; TKT-09). Reference data, not provenance:
 * no anchor; seeded idempotently by src/lib/db/seed/yield-reference.ts. `max_kg_ha` is clean coffee;
 * `cherry_to_clean_ratio` converts fresh ripe cherry to clean coffee once, at comparison.
 */
export const cropYieldReference = sqliteTable(
  'crop_yield_reference',
  {
    crop: text('crop', { enum: ['arabica', 'robusta'] }).notNull(),
    variety: text('variety').notNull(),
    minKgHa: real('min_kg_ha'),
    maxKgHa: real('max_kg_ha').notNull(),
    cherryToCleanRatio: real('cherry_to_clean_ratio').notNull(),
    source: text('source').notNull(),
    sourceUrl: text('source_url').notNull(),
    version: text('version').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.crop, t.variety] }),
    check('crop_yield_reference_crop_check', sql`${t.crop} IN ('arabica','robusta')`),
    check('crop_yield_reference_values_check', sql`${t.maxKgHa} > 0 AND ${t.cherryToCleanRatio} > 0 AND ${t.cherryToCleanRatio} <= 1`),
  ],
);

/**
 * On-chain anchoring state of each ledger entry under the EVM adapter (technical-plan TSK-24.5, TKT-24).
 * A row is inserted 'pending' in the same transaction as its ledger entry (or backfilled), and becomes
 * 'anchored' once BatchRegistry holds its entry hash; 'failed' means the chain holds a different hash.
 * Guards in the evm_anchors_guards migration: inserted pending only, never replaced or deleted, tx_hash
 * immutable once set (anchored is terminal), failed is terminal.
 */
export const evmAnchors = sqliteTable(
  'evm_anchors',
  {
    seq: integer('seq')
      .primaryKey()
      .references(() => ledgerEntries.seq),
    status: text('status', { enum: ['pending', 'anchored', 'failed'] }).notNull(),
    chainId: integer('chain_id'),
    contract: text('contract'),
    txHash: text('tx_hash'),
    blockNumber: integer('block_number'),
    attempts: integer('attempts').notNull().default(0),
    lastError: text('last_error'),
    updatedAt: text('updated_at').notNull(),
    // The operator's one resolution of a failed anchor (pnpm ledger:evm:resolve; migration 0023 guards).
    resolution: text('resolution'),
    resolvedAt: text('resolved_at'),
  },
  (t) => [
    check('evm_anchors_status_check', sql`${t.status} IN ('pending','anchored','failed')`),
    check(
      'evm_anchors_anchored_check',
      sql`(${t.status} = 'anchored') = (${t.chainId} IS NOT NULL AND ${t.contract} IS NOT NULL AND ${t.txHash} IS NOT NULL AND ${t.blockNumber} IS NOT NULL)`,
    ),
    check('evm_anchors_attempts_check', sql`${t.attempts} >= 0`),
  ],
);

/**
 * Photos uploaded ahead of their capture (technical-plan §4.1, TP28; TKT-30). A staged file belongs to
 * one agent and the phone that staged it, lives at DATA_DIR/staging/<agent_id>/<sha256> and expires
 * after an hour (swept). Not provenance: no anchor, never read by `photo_uniqueness` (only an accepted
 * capture's `media` rows count as seen). Staging the same bytes again refreshes the row.
 */
export const stagedMedia = sqliteTable(
  'staged_media',
  {
    sha256: text('sha256').notNull(),
    agentId: text('agent_id').notNull(),
    deviceId: text('device_id').notNull(),
    size: integer('size').notNull(),
    mime: text('mime').notNull(),
    path: text('path').notNull(),
    createdAt: text('created_at').notNull(),
    expiresAt: text('expires_at').notNull(),
  },
  (t) => [
    primaryKey({ columns: [t.sha256, t.agentId] }),
    index('staged_media_agent_expiry_idx').on(t.agentId, t.expiresAt),
    index('staged_media_expiry_idx').on(t.expiresAt),
  ],
);

// ── Contract farming (M-002, TKT-25; technical-plan TSK-25.4) ──────────────────────────────────────
// An agreement between a buyer and an FPO, escrowed in mock INR on ContractFarming. Every row here is
// anchored (agreement_created, agreement_funded, agreement_refunded, quality_attestation, settlement).
// Guards in the agreements custom migration: never replaced or deleted; an agreement's terms never
// change; its status moves only created → funded → settled | refunded, each step with its own anchor;
// attestations and settlements are append-only; at most one released settlement per agreement.

/** A grade on the fixed five-label scale (Design.md §28.3): Excellent 90 · Very good 80 · Good 70 · Fair 60 · Low 40. */
const GRADE_VALUES = sql`(90,80,70,60,40)`;

export const agreements = sqliteTable(
  'agreements',
  {
    /** `AG-` + 8 Crockford base32. */
    id: text('id').primaryKey(),
    /** bytes32 id on ContractFarming: `0x` + keccak256(utf8(id)). */
    chainIdHex: text('chain_id_hex').notNull().unique(),
    buyerOrg: text('buyer_org')
      .notNull()
      .references(() => organisations.id),
    fpoOrg: text('fpo_org')
      .notNull()
      .references(() => organisations.id),
    crop: text('crop', { enum: ['arabica', 'robusta'] }).notNull(),
    agreedKg: real('agreed_kg').notNull(),
    minGrade: integer('min_grade').notNull(),
    amountPaise: integer('amount_paise').notNull(),
    /** End of the deadline day in IST, as ISO-8601 UTC (`…T18:29:59.999Z`). */
    deadline: text('deadline').notNull(),
    status: text('status', { enum: ['created', 'funded', 'settled', 'refunded'] })
      .notNull()
      .default('created'),
    createdBy: text('created_by')
      .notNull()
      .references(() => user.id),
    createdAt: text('created_at').notNull(),
    createdTxHash: text('created_tx_hash').notNull(),
    anchorSeq: anchorSeq(),
    fundedAt: text('funded_at'),
    fundedTxHash: text('funded_tx_hash'),
    fundedAnchorSeq: integer('funded_anchor_seq').references(() => ledgerEntries.seq),
    /** Set with the status change to settled (the released settlement) or refunded. */
    closedAt: text('closed_at'),
    closedTxHash: text('closed_tx_hash'),
    closedAnchorSeq: integer('closed_anchor_seq').references(() => ledgerEntries.seq),
  },
  (t) => [
    check('agreements_crop_check', sql`${t.crop} IN ('arabica','robusta')`),
    check('agreements_status_check', sql`${t.status} IN ('created','funded','settled','refunded')`),
    check('agreements_kg_check', sql`${t.agreedKg} > 0`),
    check('agreements_grade_check', sql`${t.minGrade} IN ${GRADE_VALUES}`),
    check('agreements_amount_check', sql`${t.amountPaise} > 0`),
    check('agreements_orgs_check', sql`${t.buyerOrg} <> ${t.fpoOrg}`),
    check(
      'agreements_funded_check',
      sql`(${t.status} = 'created') = (${t.fundedAnchorSeq} IS NULL) AND (${t.fundedAnchorSeq} IS NULL) = (${t.fundedAt} IS NULL) AND (${t.fundedAnchorSeq} IS NULL) = (${t.fundedTxHash} IS NULL)`,
    ),
    check(
      'agreements_closed_check',
      sql`(${t.status} IN ('settled','refunded')) = (${t.closedAnchorSeq} IS NOT NULL) AND (${t.closedAnchorSeq} IS NULL) = (${t.closedAt} IS NULL) AND (${t.closedAnchorSeq} IS NULL) = (${t.closedTxHash} IS NULL)`,
    ),
    index('agreements_buyer_idx').on(t.buyerOrg),
    index('agreements_fpo_idx').on(t.fpoOrg),
  ],
);

/**
 * The buyer's quality grade for one delivered batch under an agreement (TSK-25.5). `eip712_sig` is the
 * buyer organisation's attestor key (`signer_address`) over QualityGrade(agreementId, batchIdHash,
 * grade); the anchored payload is also signed by the server on behalf of the buyer user (TP15). One
 * grade per (agreement, batch): it cannot be changed after signing.
 */
export const qualityAttestations = sqliteTable(
  'quality_attestations',
  {
    /** `QA-` + 12 Crockford base32. */
    id: text('id').primaryKey(),
    agreementId: text('agreement_id')
      .notNull()
      .references(() => agreements.id),
    batchId: text('batch_id')
      .notNull()
      .references(() => batches.id),
    grade: integer('grade').notNull(),
    signerOrg: text('signer_org')
      .notNull()
      .references(() => organisations.id),
    signerAddress: text('signer_address').notNull(),
    eip712Sig: text('eip712_sig').notNull(),
    signedBy: text('signed_by')
      .notNull()
      .references(() => user.id),
    createdAt: text('created_at').notNull(),
    anchorSeq: anchorSeq(),
  },
  (t) => [check('quality_attestations_grade_check', sql`${t.grade} IN ${GRADE_VALUES}`), unique('quality_attestations_agreement_batch_unique').on(t.agreementId, t.batchId)],
);

/**
 * One settle call's result (TSK-25.6): what the server attested (delivered kg from batch_created, whether
 * every member picking's final verdict is Verified), the signed grade, and what the contract decided.
 * `reasons` is a JSON array of the conditions not met with value vs threshold. Recorded after the
 * receipt, so `tx_hash`/`block_number` are always set. Append-only.
 */
export const settlements = sqliteTable(
  'settlements',
  {
    /** `ST-` + 12 Crockford base32. */
    id: text('id').primaryKey(),
    agreementId: text('agreement_id')
      .notNull()
      .references(() => agreements.id),
    batchId: text('batch_id')
      .notNull()
      .references(() => batches.id),
    attestationId: text('attestation_id')
      .notNull()
      .references(() => qualityAttestations.id),
    deliveredKg: real('delivered_kg').notNull(),
    pickings: integer('pickings').notNull(),
    verifiedPickings: integer('verified_pickings').notNull(),
    allVerified: integer('all_verified', { mode: 'boolean' }).notNull(),
    grade: integer('grade').notNull(),
    outcome: text('outcome', { enum: ['released', 'not_released'] }).notNull(),
    reasons: text('reasons').notNull(),
    txHash: text('tx_hash').notNull(),
    blockNumber: integer('block_number').notNull(),
    settledBy: text('settled_by')
      .notNull()
      .references(() => user.id),
    createdAt: text('created_at').notNull(),
    anchorSeq: anchorSeq(),
  },
  (t) => [
    check('settlements_outcome_check', sql`${t.outcome} IN ('released','not_released')`),
    check('settlements_grade_check', sql`${t.grade} IN ${GRADE_VALUES}`),
    check('settlements_verified_check', sql`${t.allVerified} IN (0,1) AND ${t.verifiedPickings} <= ${t.pickings} AND ${t.verifiedPickings} >= 0`),
    index('settlements_agreement_idx').on(t.agreementId),
    index('settlements_batch_idx').on(t.batchId),
    uniqueIndex('settlements_one_release_idx')
      .on(t.agreementId)
      .where(sql`${t.outcome} = 'released'`),
  ],
);
